db.origin.insertMany([
{"id_origin": "HW", "origin": "ハワイ"},
{"id_origin": "JM", "origin": "ジャマイカ"},
{"id_origin": "YE", "origin": "イエメン"},
{"id_origin": "CO", "origin": "コロンビア"},
{"id_origin": "ID", "origin": "インドネシア"},
{"id_origin": "KE", "origin": "ケニア"},
{"id_origin": "TZ", "origin": "タンザニア"},
{"id_origin": "ET", "origin": "エチオピア"},
]);

db.beans.insertMany([
{"id_beans": 1, "beans": "ハワイコナファンシー", "price": 3500, "id_origin": "HW", "acidity": 5, "bitterness": 2, "sweetness": 4, "richness": 4, "aroma": 5},
{"id_beans": 2, "beans": "ブルーマウンテンNo.1", "price": 2000, "id_origin": "JM", "acidity": 2, "bitterness": 1, "sweetness": 5, "richness": 3, "aroma": 5},
{"id_beans": 3, "beans": "モカマタリ", "price": 800, "id_origin": "YE", "acidity": 4, "bitterness": 3, "sweetness": 4, "richness": 4, "aroma": 5},
{"id_beans": 4, "beans": "エメラルドマウンテン", "price": 700, "id_origin": "CO", "acidity": 2, "bitterness": 1, "sweetness": 5, "richness": 5, "aroma": 5},
{"id_beans": 5, "beans": "マンデリンＧ１", "price": 600, "id_origin": "ID", "acidity": 2, "bitterness": 5, "sweetness": 3, "richness": 4, "aroma": 3},
{"id_beans": 6, "beans": "ケニアAA", "price": 590, "id_origin": "KE", "acidity": 5, "bitterness": 1, "sweetness": 3, "richness": 5, "aroma": 4},
{"id_beans": 7, "beans": "ジャバロブスタ", "price": 630, "id_origin": "ID", "acidity": 1, "bitterness": 5, "sweetness": 1, "richness": 3, "aroma": 1},
{"id_beans": 8, "beans": "キリマンジャロＡＡ", "price": 410, "id_origin": "TZ", "acidity": 5, "bitterness": 2, "sweetness": 4, "richness": 4, "aroma": 4},
{"id_beans": 9, "beans": "にがにがブレンド", "price": 620, "id_origin": null, "acidity": 2, "bitterness": 5, "sweetness": 3, "richness": 4, "aroma": 4},
{"id_beans": 10, "beans": "阿弗利加の風", "price": 500, "id_origin": null, "acidity": 5, "bitterness": 2, "sweetness": 4, "richness": 5, "aroma": 4},
{"id_beans": 11, "beans": "ブルーマウンテンピーベリー", "price": 2500, "id_origin": "JM", "acidity": 3, "bitterness": 1, "sweetness": 5, "richness": 3, "aroma": 4},
{"id_beans": 12, "beans": "コロンビアスプレモ", "price": 410, "id_origin": "CO", "acidity": 3, "bitterness": 1, "sweetness": 4, "richness": 5, "aroma": 4},
]);

db.review.insertMany([
{"user": {"id": 1, "name": "レビュアー1", "genderAge": "F2"}, "star": 2, "keywords": ["酸味", "爽やか"], "review": "このコーヒーは酸味が特徴で、爽やかが楽しめます。 期待していたほどの深みは感じられませんでした。", "timestamp": {"$date": "2021-09-01T00:00:00Z"}, "beans": "ハワイコナファンシー", "id_beans": 1},
{"user": {"id": 1, "name": "レビュアー1", "genderAge": "F2"}, "star": 5, "keywords": ["酸味", "爽やか"], "review": "これ以上のコーヒーはないと言っても過言ではありません。まさに芸術品です。", "timestamp": {"$date": "2022-07-06T00:00:00Z"}, "beans": "ブルーマウンテンNo.1", "id_beans": 2},
{"user": {"id": 1, "name": "レビュアー1", "genderAge": "F2"}, "star": 5, "keywords": ["酸味", "爽やか"], "review": "過去最高のコーヒー体験でした。洗練された風味が感動を与えてくれます。", "timestamp": {"$date": "2024-08-06T00:00:00Z"}, "beans": "モカマタリ", "id_beans": 3},
{"user": {"id": 1, "name": "レビュアー1", "genderAge": "F2"}, "star": 5, "keywords": ["スパイシー", "個性派"], "review": "濃厚でありながら繊細な味わい。まるで特別な瞬間のために用意されたような豆です。", "timestamp": {"$date": "2024-04-08T00:00:00Z"}, "beans": "エメラルドマウンテン", "id_beans": 4},
{"user": {"id": 1, "name": "レビュアー1", "genderAge": "F2"}, "star": 5, "keywords": ["スパイシー", "個性派"], "review": "これはまさに極上の一杯です。香り、味わい、余韻のすべてが完璧でした。", "timestamp": {"$date": "2020-06-02T00:00:00Z"}, "beans": "マンデリンＧ１", "id_beans": 5},
{"user": {"id": 1, "name": "レビュアー1", "genderAge": "F2"}, "star": 3, "keywords": ["香り高い", "濃厚"], "review": "濃厚を感じさせる香りと、香り高いな味わいが魅力です。", "timestamp": {"$date": "2022-12-23T00:00:00Z"}, "beans": "ケニアAA", "id_beans": 6},
{"user": {"id": 1, "name": "レビュアー1", "genderAge": "F2"}, "star": 4, "keywords": ["苦味", "余韻"], "review": "苦味と余韻が絶妙に調和した逸品です。", "timestamp": {"$date": "2023-03-20T00:00:00Z"}, "beans": "ジャバロブスタ", "id_beans": 7},
{"user": {"id": 1, "name": "レビュアー1", "genderAge": "F2"}, "star": 1, "keywords": ["高級", "アロマ"], "review": "雑味が強く、飲むに堪えないレベルでした。", "timestamp": {"$date": "2021-09-19T00:00:00Z"}, "beans": "キリマンジャロＡＡ", "id_beans": 8},
{"user": {"id": 1, "name": "レビュアー1", "genderAge": "F2"}, "star": 3, "keywords": ["深煎り", "コク"], "review": "コクを感じさせる香りと、深煎りな味わいが魅力です。", "timestamp": {"$date": "2023-09-16T00:00:00Z"}, "beans": "にがにがブレンド", "id_beans": 9},
{"user": {"id": 1, "name": "レビュアー1", "genderAge": "F2"}, "star": 3, "keywords": ["スパイシー", "個性派"], "review": "このコーヒーはスパイシーが特徴で、個性派が楽しめます。", "timestamp": {"$date": "2024-08-21T00:00:00Z"}, "beans": "阿弗利加の風", "id_beans": 10},
{"user": {"id": 1, "name": "レビュアー1", "genderAge": "F2"}, "star": 4, "keywords": ["深煎り", "コク"], "review": "飲み口が深煎りで、後味にコクが残ります。", "timestamp": {"$date": "2022-06-28T00:00:00Z"}, "beans": "ブルーマウンテンピーベリー", "id_beans": 11},
{"user": {"id": 1, "name": "レビュアー1", "genderAge": "F2"}, "star": 3, "keywords": ["酸味", "爽やか"], "review": "飲み口が酸味で、後味に爽やかが残ります。", "timestamp": {"$date": "2024-10-22T00:00:00Z"}, "beans": "コロンビアスプレモ", "id_beans": 12},
{"user": {"id": 3, "name": "レビュアー3", "genderAge": "M1"}, "star": 3, "keywords": ["香り高い", "濃厚"], "review": "このコーヒーは香り高いが特徴で、濃厚が楽しめます。", "timestamp": {"$date": "2023-09-03T00:00:00Z"}, "beans": "阿弗利加の風", "id_beans": 10},
{"user": {"id": 5, "name": "レビュアー5", "genderAge": "M3"}, "star": 3, "keywords": ["酸味", "爽やか"], "review": "酸味な風味が口に広がり、爽やかが印象的でした。", "timestamp": {"$date": "2023-09-09T00:00:00Z"}, "beans": "ケニアAA", "id_beans": 6},
{"user": {"id": 2, "name": "レビュアー2", "genderAge": "F1"}, "star": 2, "keywords": ["マイルド", "軽やか"], "review": "このコーヒーはマイルドが特徴で、軽やかが楽しめます。 期待していたほどの深みは感じられませんでした。", "timestamp": {"$date": "2021-05-18T00:00:00Z"}, "beans": "にがにがブレンド", "id_beans": 9},
{"user": {"id": 10, "name": "レビュアー10", "genderAge": "M1"}, "star": 5, "keywords": ["マイルド", "軽やか"], "review": "一口飲んだ瞬間に感動しました。香り高く、豊かな味わいが長く続きます。", "timestamp": {"$date": "2023-08-13T00:00:00Z"}, "beans": "エメラルドマウンテン", "id_beans": 4},
{"user": {"id": 8, "name": "レビュアー8", "genderAge": "M1"}, "star": 5, "keywords": ["深煎り", "コク"], "review": "濃厚でありながら繊細な味わい。まるで特別な瞬間のために用意されたような豆です。", "timestamp": {"$date": "2022-02-14T00:00:00Z"}, "beans": "エメラルドマウンテン", "id_beans": 4},
{"user": {"id": 4, "name": "レビュアー4", "genderAge": "M3"}, "star": 2, "keywords": ["深煎り", "コク"], "review": "深煎りな風味が口に広がり、コクが印象的でした。 しかし、後味に雑味が残る印象があります。", "timestamp": {"$date": "2020-08-08T00:00:00Z"}, "beans": "にがにがブレンド", "id_beans": 9},
{"user": {"id": 10, "name": "レビュアー10", "genderAge": "M1"}, "star": 4, "keywords": ["苦味", "余韻"], "review": "苦味と余韻が絶妙に調和した逸品です。", "timestamp": {"$date": "2021-06-11T00:00:00Z"}, "beans": "ブルーマウンテンNo.1", "id_beans": 2},
{"user": {"id": 2, "name": "レビュアー2", "genderAge": "F1"}, "star": 3, "keywords": ["スパイシー", "個性派"], "review": "個性派を感じさせる香りと、スパイシーな味わいが魅力です。", "timestamp": {"$date": "2021-10-08T00:00:00Z"}, "beans": "マンデリンＧ１", "id_beans": 5},
{"user": {"id": 5, "name": "レビュアー5", "genderAge": "M3"}, "star": 3, "keywords": ["苦味", "余韻"], "review": "苦味と余韻が絶妙に調和した逸品です。", "timestamp": {"$date": "2024-05-17T00:00:00Z"}, "beans": "エメラルドマウンテン", "id_beans": 4},
{"user": {"id": 5, "name": "レビュアー5", "genderAge": "M3"}, "star": 4, "keywords": ["香り高い", "濃厚"], "review": "香り高いな風味が口に広がり、濃厚が印象的でした。", "timestamp": {"$date": "2023-04-11T00:00:00Z"}, "beans": "モカマタリ", "id_beans": 3},
{"user": {"id": 6, "name": "レビュアー6", "genderAge": "F2"}, "star": 3, "keywords": ["マイルド", "軽やか"], "review": "マイルドと軽やかが絶妙に調和した逸品です。", "timestamp": {"$date": "2021-11-23T00:00:00Z"}, "beans": "マンデリンＧ１", "id_beans": 5},
{"user": {"id": 7, "name": "レビュアー7", "genderAge": "M1"}, "star": 5, "keywords": ["スパイシー", "個性派"], "review": "これはまさに極上の一杯です。香り、味わい、余韻のすべてが完璧でした。", "timestamp": {"$date": "2022-06-18T00:00:00Z"}, "beans": "エメラルドマウンテン", "id_beans": 4},
{"user": {"id": 7, "name": "レビュアー7", "genderAge": "M1"}, "star": 4, "keywords": ["高級", "アロマ"], "review": "高級な風味が口に広がり、アロマが印象的でした。", "timestamp": {"$date": "2021-10-10T00:00:00Z"}, "beans": "モカマタリ", "id_beans": 3},
{"user": {"id": 5, "name": "レビュアー5", "genderAge": "M3"}, "star": 3, "keywords": ["苦味", "余韻"], "review": "苦味な風味が口に広がり、余韻が印象的でした。", "timestamp": {"$date": "2021-08-07T00:00:00Z"}, "beans": "マンデリンＧ１", "id_beans": 5},
{"user": {"id": 2, "name": "レビュアー2", "genderAge": "F1"}, "star": 4, "keywords": ["深煎り", "コク"], "review": "飲み口が深煎りで、後味にコクが残ります。", "timestamp": {"$date": "2022-08-15T00:00:00Z"}, "beans": "モカマタリ", "id_beans": 3},
{"user": {"id": 3, "name": "レビュアー3", "genderAge": "M1"}, "star": 5, "keywords": ["深煎り", "コク"], "review": "これ以上のコーヒーはないと言っても過言ではありません。まさに芸術品です。", "timestamp": {"$date": "2023-03-25T00:00:00Z"}, "beans": "ブルーマウンテンピーベリー", "id_beans": 11},
{"user": {"id": 3, "name": "レビュアー3", "genderAge": "M1"}, "star": 5, "keywords": ["深煎り", "コク"], "review": "これはまさに極上の一杯です。香り、味わい、余韻のすべてが完璧でした。", "timestamp": {"$date": "2022-07-23T00:00:00Z"}, "beans": "ケニアAA", "id_beans": 6},
{"user": {"id": 2, "name": "レビュアー2", "genderAge": "F1"}, "star": 5, "keywords": ["深煎り", "コク"], "review": "一口飲んだ瞬間に感動しました。香り高く、豊かな味わいが長く続きます。", "timestamp": {"$date": "2023-01-12T00:00:00Z"}, "beans": "ブルーマウンテンNo.1", "id_beans": 2},
{"user": {"id": 6, "name": "レビュアー6", "genderAge": "F2"}, "star": 4, "keywords": ["スパイシー", "個性派"], "review": "飲み口がスパイシーで、後味に個性派が残ります。", "timestamp": {"$date": "2021-10-30T00:00:00Z"}, "beans": "ハワイコナファンシー", "id_beans": 1},
{"user": {"id": 5, "name": "レビュアー5", "genderAge": "M3"}, "star": 4, "keywords": ["高級", "アロマ"], "review": "このコーヒーは高級が特徴で、アロマが楽しめます。", "timestamp": {"$date": "2020-07-02T00:00:00Z"}, "beans": "にがにがブレンド", "id_beans": 9},
{"user": {"id": 8, "name": "レビュアー8", "genderAge": "M1"}, "star": 3, "keywords": ["高級", "アロマ"], "review": "このコーヒーは高級が特徴で、アロマが楽しめます。", "timestamp": {"$date": "2024-07-18T00:00:00Z"}, "beans": "阿弗利加の風", "id_beans": 10},
{"user": {"id": 5, "name": "レビュアー5", "genderAge": "M3"}, "star": 3, "keywords": ["高級", "アロマ"], "review": "高級とアロマが絶妙に調和した逸品です。", "timestamp": {"$date": "2024-02-19T00:00:00Z"}, "beans": "コロンビアスプレモ", "id_beans": 12},
{"user": {"id": 4, "name": "レビュアー4", "genderAge": "M3"}, "star": 4, "keywords": ["高級", "アロマ"], "review": "アロマを感じさせる香りと、高級な味わいが魅力です。", "timestamp": {"$date": "2023-10-27T00:00:00Z"}, "beans": "マンデリンＧ１", "id_beans": 5},
{"user": {"id": 10, "name": "レビュアー10", "genderAge": "M1"}, "star": 1, "keywords": ["深煎り", "コク"], "review": "風味が全く感じられず、非常にがっかりしました。", "timestamp": {"$date": "2021-05-12T00:00:00Z"}, "beans": "コロンビアスプレモ", "id_beans": 12},
{"user": {"id": 3, "name": "レビュアー3", "genderAge": "M1"}, "star": 3, "keywords": ["酸味", "爽やか"], "review": "爽やかを感じさせる香りと、酸味な味わいが魅力です。", "timestamp": {"$date": "2022-05-25T00:00:00Z"}, "beans": "ハワイコナファンシー", "id_beans": 1},
{"user": {"id": 5, "name": "レビュアー5", "genderAge": "M3"}, "star": 4, "keywords": ["マイルド", "軽やか"], "review": "このコーヒーはマイルドが特徴で、軽やかが楽しめます。", "timestamp": {"$date": "2020-12-31T00:00:00Z"}, "beans": "キリマンジャロＡＡ", "id_beans": 8},
{"user": {"id": 6, "name": "レビュアー6", "genderAge": "F2"}, "star": 4, "keywords": ["スパイシー", "個性派"], "review": "個性派を感じさせる香りと、スパイシーな味わいが魅力です。", "timestamp": {"$date": "2022-09-07T00:00:00Z"}, "beans": "キリマンジャロＡＡ", "id_beans": 8},
{"user": {"id": 10, "name": "レビュアー10", "genderAge": "M1"}, "star": 4, "keywords": ["酸味", "爽やか"], "review": "このコーヒーは酸味が特徴で、爽やかが楽しめます。", "timestamp": {"$date": "2020-01-16T00:00:00Z"}, "beans": "ジャバロブスタ", "id_beans": 7},
{"user": {"id": 2, "name": "レビュアー2", "genderAge": "F1"}, "star": 5, "keywords": ["香り高い", "濃厚"], "review": "これはまさに極上の一杯です。香り、味わい、余韻のすべてが完璧でした。", "timestamp": {"$date": "2020-12-06T00:00:00Z"}, "beans": "ハワイコナファンシー", "id_beans": 1},
{"user": {"id": 6, "name": "レビュアー6", "genderAge": "F2"}, "star": 1, "keywords": ["苦味", "余韻"], "review": "風味が全く感じられず、非常にがっかりしました。", "timestamp": {"$date": "2020-02-18T00:00:00Z"}, "beans": "ジャバロブスタ", "id_beans": 7},
{"user": {"id": 9, "name": "レビュアー9", "genderAge": "M3"}, "star": 5, "keywords": ["酸味", "爽やか"], "review": "これ以上のコーヒーはないと言っても過言ではありません。まさに芸術品です。", "timestamp": {"$date": "2020-04-23T00:00:00Z"}, "beans": "ブルーマウンテンピーベリー", "id_beans": 11},
{"user": {"id": 3, "name": "レビュアー3", "genderAge": "M1"}, "star": 5, "keywords": ["香り高い", "濃厚"], "review": "濃厚でありながら繊細な味わい。まるで特別な瞬間のために用意されたような豆です。", "timestamp": {"$date": "2021-09-09T00:00:00Z"}, "beans": "エメラルドマウンテン", "id_beans": 4},
{"user": {"id": 7, "name": "レビュアー7", "genderAge": "M1"}, "star": 5, "keywords": ["バランス", "甘み"], "review": "一口飲んだ瞬間に感動しました。香り高く、豊かな味わいが長く続きます。", "timestamp": {"$date": "2020-07-16T00:00:00Z"}, "beans": "コロンビアスプレモ", "id_beans": 12},
{"user": {"id": 2, "name": "レビュアー2", "genderAge": "F1"}, "star": 3, "keywords": ["香り高い", "濃厚"], "review": "香り高いと濃厚が絶妙に調和した逸品です。", "timestamp": {"$date": "2020-03-11T00:00:00Z"}, "beans": "コロンビアスプレモ", "id_beans": 12},
{"user": {"id": 10, "name": "レビュアー10", "genderAge": "M1"}, "star": 2, "keywords": ["高級", "アロマ"], "review": "アロマを感じさせる香りと、高級な味わいが魅力です。 しかし、後味に雑味が残る印象があります。", "timestamp": {"$date": "2024-03-12T00:00:00Z"}, "beans": "モカマタリ", "id_beans": 3},
{"user": {"id": 9, "name": "レビュアー9", "genderAge": "M3"}, "star": 2, "keywords": ["酸味", "爽やか"], "review": "酸味と爽やかが絶妙に調和した逸品です。 しかし、後味に雑味が残る印象があります。", "timestamp": {"$date": "2021-01-15T00:00:00Z"}, "beans": "にがにがブレンド", "id_beans": 9},
{"user": {"id": 8, "name": "レビュアー8", "genderAge": "M1"}, "star": 5, "keywords": ["マイルド", "軽やか"], "review": "過去最高のコーヒー体験でした。洗練された風味が感動を与えてくれます。", "timestamp": {"$date": "2021-05-05T00:00:00Z"}, "beans": "ブルーマウンテンピーベリー", "id_beans": 11},
{"user": {"id": 5, "name": "レビュアー5", "genderAge": "M3"}, "star": 4, "keywords": ["苦味", "余韻"], "review": "このコーヒーは苦味が特徴で、余韻が楽しめます。", "timestamp": {"$date": "2023-11-02T00:00:00Z"}, "beans": "ブルーマウンテンピーベリー", "id_beans": 11},
])
